# code: language=ansible
---
- name: Set temp vars
  ansible.builtin.set_fact:
    __trimmedVersion: "{{ node_exporter_version[1:] }}"

- name: Check current node_exporter version.
  ansible.builtin.command: "{{ node_exporter_bin_path }} --version"
  failed_when: false
  changed_when: false
  register: node_exporter_version_check

- name: Download and unarchive node_exporter into temporary location.
  ansible.builtin.unarchive:
    src: "{{ node_exporter_download_url }}"
    dest: /tmp
    remote_src: true
    mode: "0755"
  when: >
    node_exporter_version_check.stdout is not defined
    or __trimmedVersion not in node_exporter_version_check.stdout
  register: node_exporter_download_check

- name: Move node_exporter binary into place.
  become: true
  ansible.builtin.copy:
    src: "/tmp/node_exporter-{{ __trimmedVersion }}.linux-{{ node_exporter_arch }}/node_exporter"
    dest: "{{ node_exporter_bin_path }}"
    mode: "0755"
    remote_src: true
    owner: root
    group: root
  notify: Restart node_exporter
  register: node_exporter_copy
  when: node_exporter_download_check is changed # noqa: no-handler

- name: Delete binary from temp path
  ansible.builtin.file:
    path: "/tmp/node_exporter-{{ __trimmedVersion }}.linux-{{ node_exporter_arch }}/node_exporter"
    state: absent

- name: Create node_exporter group (optional fixed GID)
  become: true
  ansible.builtin.group:
    name: node_exporter
    gid: "{{ node_exporter_gid | default(omit) }}"
    state: present
  when: "node_exporter_gid is defined"

- name: Create node_exporter user (optional fixed UID)
  become: true
  ansible.builtin.user:
    name: node_exporter
    shell: /sbin/nologin
    create_home: false
    uid: "{{ node_exporter_uid | default(omit) }}"
    group: "{{ (node_exporter_gid is defined) | ternary('node_exporter', omit) }}"
    state: present

- name: Copy the node_exporter systemd unit file.
  when: ansible_facts['service_mgr'] == "systemd"
  become: true
  ansible.builtin.template:
    src: node_exporter.systemd.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: "0644"
    owner: root
    group: root
  register: node_exporter_service
  notify: Restart node_exporter

- name: Reload systemd daemon if unit file is changed.
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  when: node_exporter_service is changed and ansible_facts['service_mgr'] == "systemd" # noqa: no-handler

- name: Template openrc unit file
  become: true
  when: ansible_facts['service_mgr'] == "openrc"
  ansible.builtin.template:
    src: node_exporter.openrc.j2
    dest: /etc/init.d/node_exporter
    owner: root
    group: root
    mode: "0744"
  notify: Restart node_exporter

- name: Ensure node_exporter is running and enabled at boot.
  become: true
  ansible.builtin.service:
    name: node_exporter
    state: "{{ node_exporter_state }}"
    enabled: "{{ node_exporter_enabled }}"

- name: Verify node_exporter is responding to requests.
  ansible.builtin.uri:
    url: "http://{% if node_exporter_host != '' %}{{ node_exporter_host }}{% else %}localhost{% endif %}:{{ node_exporter_port }}/"
    return_content: true
  register: metrics_output
  failed_when: "'Metrics' not in metrics_output.content"
